API/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.getQuiz) ,
  path('/tag',views.survey_view) 
  ]

Feedback/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dev/api', include("API.urls")),
    path('',include("survey.urls")),
]

survey/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Default path is /survey/ which invokes index view without any params
    path('', views.index, name="index"),

    # API GET endpoint for returning popular survey among existing surveys.
    # This endpoint can also be used as a web hook in future. Currently it is used within the application.
    path('get_popular_survey/', views.get_popular_survey, name="get_popular_survey"),

    # API GET endpoint for returning survey objects along with corresponding questions and choices.
    # This endpoint can also be used as a web hook in future. Currently it is used within the application.
    path('get_all_surveys/', views.get_all_surveys, name="get_all_surveys"),

    # This is the view hook to submit survey form,
    # update entities based on the submitted form and redirect to success page
    path('submit_survey/', views.submit_survey, name="submit_survey"),

    # This is the generic route for rendering all partial views without params
    # All routes are intercepted by index view middleware and respective partial view will be rendered accordingly
    # Note: This is a work around as at this point I could not find a better solution
    # or documentation to create partial views
    path('<str:partial_view>/', views.index, name="index/partial_view"),

    # This is the generic route for rendering partial views with id parameter
    path('<str:partial_view>/<int:pk>', views.index, name="index/partial_view/id"),
]

survey/models.py
from django.db import models
# import jsonfield
import jsonfield

# Create your models here.
class Survey(models.Model):
  survey_id = models.CharField(max_length=50,primary_key=True)
  date_posted = models.DateField()
  survey_name = models.CharField(max_length=50)

  def __str__(self):
    return self.survey_name
  
class Question(models.Model):
  q_id = models.CharField(max_length = 50,primary_key=50)
  q_no = models.IntegerField()
  quiz = models.CharField(max_length=250)
  q_tag = models.CharField(max_length=50 , unique=True,null=True)
  survey_id = models.ForeignKey(Survey, on_delete=models.CASCADE)
  options = jsonfield.JSONField()
  
  def __str__(self):
    return self.quiz
  
# class Option(models.Model):
#   q_id = models.ForeignKey(Question, on_delete=models.CASCADE)
#   opt1 = models.CharField(max_length=50)
#   opt2 = models.CharField(max_length=50)
#   opt3 = models.CharField(max_length=50)
#   opt4 = models.CharField(max_length=50)

  
  
class Response(models.Model):
  q_tag = models.ForeignKey(Question, on_delete=models.CASCADE, to_field='q_tag')

  survey_id = models.ForeignKey(Survey, on_delete=models.CASCADE)
  response = models.CharField(max_length=50)

survey/views.py
"""Create Views for the application

Here you can create views for the survey application.
Each view will be either mapped directly to a URL in the routing
or will be used to render partial views using inclusion_tags.

index:
------
This is the default view for the start site of the application.
Also, this is a middleware for routing requests to partial views.
all_partial_views: is a list of partial views that are registered with index.
Default partial view is 'about'.

all_surveys:
------------
This is the partial view rendering list of surveys created by the admin.
Context object is currently not being used.
However, it is a required param for invoking the view from inclusion template tag.

about:
------
This is the partial view for rendering about page. The view only displays static content.

survey_details:
---------------
This is the partial view for the survey form. It accepts survey id as querystring parameter.
It provides survey details for the survey id provided for the html template.

submit_success:
---------------
This is the partial view for displaying submit success message.

submit_survey:
--------------
This is the hook for form submit which gets the voted choices.
From this it increments the votes of respective choices.
Also, it creates a participant instance tracking the survey participation
and the datetime at which the survey was taken.

get_popular_survey:
-------------------
This is the API GET endpoint for returning popular survey among existing surveys.
This endpoint can also be used as a web hook in future. Currently it is used within the application.

get_all_surveys:
----------------
API GET endpoint for returning survey objects along with corresponding questions and choices.
This endpoint can also be used as a web hook in future. Currently it is used within the application.

"""

from django.shortcuts import render, redirect
from django.http import Http404, HttpResponse, JsonResponse
from django.template.loader_tags import register
from django.views.decorators.http import require_http_methods
from .models import Survey, Question
from django.utils import timezone
from django.db.models import Count
from django.core import serializers
import operator

all_partial_views = ['home', 'Chart','all_surveys', 'survey_details', 'submit_success']


@require_http_methods(["GET"])
def index(request, partial_view, pk=None):
    if partial_view is None:
        print("none partialing")
        partial_view = 'home'
        return render(request, 'survey/index.html', {"partial_view": partial_view, "pk": pk})
    elif all_partial_views.count(partial_view) == 0:
        raise Http404('Partial View not found!')
    elif partial_view == "survey_details" and pk is None:
        raise Http404('Invalid Address! Page Not Found')
    else:
        print("none partial")
        return render(request, 'survey/index.html', {"partial_view": partial_view, "pk": pk})

@register.inclusion_tag('survey/surveys.html', takes_context=True)
def all_surveys(context):
    surveys = Survey.objects.all()
    return {'surveys': surveys}


@register.inclusion_tag('survey/home.html', takes_context=True)
def home(context):
    return {}

@register.inclusion_tag('survey/Chart.html', takes_context=True)
def Chart(context):
    return {}


@register.inclusion_tag('survey/survey_details.html', takes_context=True)
def survey_details(context, survey_id):
    survey = Survey.objects.get(id=survey_id)
    return {'survey': survey}


@register.inclusion_tag('survey/submit_success.html', takes_context=True)
def submit_success(context):
    return {}


@require_http_methods(["POST"])
def submit_survey(request):
    form_data = request.POST.copy()
    # Example: {'csrfmiddlewaretoken': ['idT13LGpggg78Yr0rU3vSkT1PQxnM9hT7z97FvuZEBb
    # IU2acygAUr2W3FE9SCGbk'], '1': ['choice/3'], '2': ['choice/5']}
    form_items = list(form_data.items())
    print("form_items", form_items)
    form_items.pop(0)  # the first element is the csrf token. Therefore omit it.
    survey = None
    for item in form_items:
        # Here in 'choice/3', '3' is '<choice_id>'.
        choice_str, choice_id = item
        choice_id = int(choice_id.split('/')[1])
        choice = C.objects.get(id=choice_id)
        if survey is None:
            survey = choice.question.survey
        choice.votes = choice.votes + 1
        choice.save()
    if survey is not None:
        participant = Participant(survey=survey, participation_datetime=timezone.now())
        participant.save()
    return redirect('/survey/submit_success/')


@require_http_methods(["GET"])
def get_popular_survey(request):
    popular_survey_id = None
    popular_survey = None
    surveys = Survey.objects.all()
    survey_participants_dict = {}
    for survey in surveys:
        num_participants = Participant.objects.filter(survey=survey).count()
        survey_participants_dict[survey.id] = num_participants
    if len(survey_participants_dict) > 0:
        popular_survey_id = max(survey_participants_dict.items(), key=operator.itemgetter(1))[0]
    if popular_survey_id is not None:
        popular_survey = serializers.serialize("json", surveys.filter(id=popular_survey_id))
    return JsonResponse(popular_survey, safe=False)


#@require_http_methods(["GET"])
#def get_all_surveys(request):
    surveys = Survey.objects.all()
    questions = Question.objects.all()
    choices = Choice.objects.all()

    return JsonResponse({"surveys": serializers.serialize("json", surveys),
                         "questions": serializers.serialize("json", questions),
                         "choices": serializers.serialize("json", choices)})


@require_http_methods(["GET"])
def get_all_surveys(request):
    surveys = Survey.objects.all()
    questions = Question.objects.all()
    choices = Choice.objects.all()
    
    # Get response data grouped by choice and question
    response_data = Response.objects.values('choice__text', 'question__text').annotate(count=Count('id'))
    
    # Transform response data into series data for Highcharts
    series_data = {}
    for response in response_data:
        question = response['question__text']
        choice = response['choice__text']
        count = response['count']
        if question not in series_data:
            series_data[question] = []
        series_data[question].append({'name': choice, 'y': count})
    
    # Transform series data into Highcharts format
    chart_data = []
    chart_type = request.GET.get('chart_type', 'column')
    for question, data in series_data.items():
        chart_data.append({
            'name': question,
            'data': data,
            'type': chart_type
        })

    return JsonResponse({"surveys": serializers.serialize("json", surveys),
                         "questions": serializers.serialize("json", questions),
                         "choices": serializers.serialize("json", choices),
                         "chart_data": chart_data})

survey/templates/survey/Chart.html
<!DOCTYPE html>
<html>
  <head>
    <title>Highcharts Example</title>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
  </head>
  <body>
    <div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
    <script>
      Highcharts.chart('container', {
        title: {
          text: 'KEMRI ANNUAL LAB SURVEYS',
          x: -20
        },
        subtitle: {
          text: 'KEMRI SURVEYS',
          x: -20
        },
        xAxis: {
          categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                       'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
        },
        yAxis: {
          title: {
            text: 'Respondents'
          },
          plotLines: [{
            value: 0,
            width: 1,
            color: '#808080'
          }]
        },
        tooltip: {
          valueSuffix: '°C'
        },
        series: [{
          name: 'Kisumu Central',
          data: [7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]
        }, {
          name: 'Kisumu West',
          data: [-0.2, 0.8, 5.7, 11.3, 17.0, 22.0, 24.8, 24.1, 20.1, 14.1, 8.6, 2.5]
        }, {
          name: 'Kisumu East',
          data: [-0.9, 0.6, 3.5, 8.4, 13.5, 17.0, 18.6, 17.9, 14.3, 9.0, 3.9, 1.0]
        }, {
          name: 'Kisumu North',
          data: [3.9, 4.2, 5.7, 8.5, 11.9, 15.2, 17.0, 16.6, 14.2, 10.3, 6.6, 4.8]
        }]
      });
    </script>
  </body>
</html>

survey/templates/survey/facility.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'facility.css'%}">
    <link href="{% static 'style.css'%}" type="text/css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Average+Sans&family=Open+Sans&display=swap"
     rel="stylesheet">
    <title>Facility form</title>
</head>
<body>
    <div class="header">
        <img src="https://eiddash.nascop.org/img/nascoplogo.png" >
    </div>
    <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="col-md-4 col-sm-4 col-xs-12"></div>
                        <div class="col-md-4 col-sm-4 col-xs-12"></div>
                        <header class="header">
                          <h1 style="color:black;"> Feedback Form</h1>
                        </header>
                        <form class="form-container">
                          
                            <div class="form-group">
 <label for="Inputusername" class="form-label" style=" font-weight: 800; font-size:medium; ">Facility:</label> <br>

  <div id="username">
    <input id="search" name="myURL" type="url" placeholder="Search for facility" />
</div>
 
</div><br>

                            <div class="form-group">
<label for="InputPassword1" class="form-label"  style="font-weight: 800; font-size:medium; "> Batch no:</label><br>
<div id="password">
    <svg height="20px" xmlns="http://www.w3.org/2000/svg" fill="" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
        <path strokeLinecap="round" strokeLinejoin="round" d="M16.5 10.5V6.75a4.5 4.5 0 10-9 0v3.75m-.75 11.25h10.5a2.25 2.25 0 002.25-2.25v-6.75a2.25 2.25 0 00-2.25-2.25H6.75a2.25 2.25 0 00-2.25 2.25v6.75a2.25 2.25 0 002.25 2.25z" />
      </svg>
      <input type="password" class="form-control" id="Batchno" placeholder="Password" style="height: 24px;"></div><br>

</div> 
  
                            
<div id="login">
<button type="LOGIN" class="btn btn-success btn-block" >LOGIN</button><br>
</div>
<div id="here">
    <button type="LOGIN" class="btn btn-success btn-block"> <a href="index.html"> Labaratory Login</a> </button>
    </div>         
    </form>
                          
                        
    <div>
        <h4 style="color: gray; text-align: center; font-weight: 200; padding-top: 30px;"> <strong style="color: gray; text-align: center; font-weight: 200;">© NASCOP</strong> - 1987 - 2023 | All Rights Reserved.</h4>
     </div>

            </div>
    
          
</body>
</html>

survey/templates/survey/home.html
{% load static %}
<link rel="stylesheet" href="{% static 'design.css'%}">

  <div class="about-image">
    <image src = "{% static 'kemri_logo.jpg'%}"></image>
  </div>
  <div class="about-card"></br>
  <h2>
    KEMRI LABORATORY FOR MOLECULAR BIOLOGY CUSTOMER SATISFACTION SURVEY.
  </h3>
    <p>The customer survey for KEMRI Laboratory for Molecular Biology is
      intended to gather feedback from its customers about their experiences and
        satisfaction with the laboratory's services. The survey will include
        questions about the quality of service, the timeliness of results, 
        the accuracy of tests, the professionalism of staff, and the overall 
        experience of working with the laboratory. The survey will also seek 
        suggestions for improvement and areas where the laboratory can enhance its services. 
        The data collected from the survey will be used to identify areas of
          strength and weakness in the laboratory's operations and to develop strategies
          to improve customer satisfaction and overall service quality.
    </p><br>
  </div>

survey/templates/survey/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/survey-app.css' %}">
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <title> Application</title>
</head>
{% load static %}
<body style="background-image: url('{% static 'img/background.jpg' %}')">
    <nav class="navbar navbar-expand-lg dark" style="background-color: #333;">
      <a class="navbar-brand survey-navbar-link" href="#"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% if partial_view == "home" %}
                <li class="nav-item active">
                    <a class="nav-link survey-navbar-link" href="/home/">Home<span class="sr-only">(current)</span></a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link survey-navbar-link" href="/home/">Home</a>
                </li>
            {% endif %}
            {% if partial_view == "all_surveys" %}
                <li class="nav-item active">
                    <a class="nav-link survey-navbar-link" href="/all_surveys/">Surveys <span class="sr-only">(current)</span></a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link survey-navbar-link" href="/all_surveys/">Surveys</a>
                </li>
            {% endif %}
            {% if partial_view == "Chart" %}
                <li class="nav-item active">
                    <a class="nav-link survey-navbar-link" href="/Chart/">SurveyAdmin <span class="sr-only">(current)</span></a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link survey-navbar-link" href="/Chart/">SurveyAdmin</a>
                </li>
            {% endif %}
            
            <li class="nav-item">
                <a class="nav-link survey-navbar-link" href="/admin/">Admin Page</a>
            </li>

      </div>
      
    </nav>
        {% if partial_view == 'home' %}
            {% home %}
        {% endif %}
        {% if partial_view == 'Chart' %}
            {% Chart %}
        {% endif %}
        {% if partial_view == 'all_surveys' %}
            {% all_surveys %}
        {% endif %}
        {% if partial_view == 'survey_details' %}
            {% survey_details pk %}
        {% endif %}
        {% if partial_view == 'submit_success' %}
            {% submit_success %}
        {% endif %}

</body>
</html>

survey/templates/survey/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css'%}">
    <link href="{% static 'style.css'%}" type="text/css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Average+Sans&family=Open+Sans&display=swap"
     rel="stylesheet">
    <title>Feedback Login form</title>
</head>
<body>
    <div class="header">
        <img src="https://eiddash.nascop.org/img/nascoplogo.png" >
    </div>
    <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="col-md-4 col-sm-4 col-xs-12"></div>
                        <div class="col-md-4 col-sm-4 col-xs-12"></div>
                        <header class="header">
                          <h1 style="color:black;"> Feedback Form</h1>
                        </header>
                        <form class="form-container">
                          
                            <div class="form-group">
 <label for="Inputusername" class="form-label" style=" font-weight: 800; font-size:medium; " >Facility name:</label> <br>

  <div id="username">
    <svg  height="20px" xmlns="http://www.w3.org/2000/svg" fill="" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
        <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
      </svg>
      <input type="username" class="form-control" id="Inputusername" placeholder="Username">
  </div>
 
</div><br>

                            <div class="form-group">
<label for="InputPassword1" class="form-label"> Password:</label><br>
<div id="password">
    <svg height="20px" xmlns="http://www.w3.org/2000/svg" fill="" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
        <path strokeLinecap="round" strokeLinejoin="round" d="M16.5 10.5V6.75a4.5 4.5 0 10-9 0v3.75m-.75 11.25h10.5a2.25 2.25 0 002.25-2.25v-6.75a2.25 2.25 0 00-2.25-2.25H6.75a2.25 2.25 0 00-2.25 2.25v6.75a2.25 2.25 0 002.25 2.25z" />
      </svg>
      <input type="password" class="form-control" id="InputPassword1" placeholder="Password" style="height: 24px;"></div><br>

</div> 
  
                            <div class="checkbox">
<input type="checkbox" class="form-check-input" id="Check1">
<label class="form-check-label" for="Check1">Remember me</label>
                            </div>
                            <br>
                            
<div id="login">
<button type="LOGIN" class="btn btn-success btn-block" >LOGIN</button><br>
</div>
<div id="here">
<button type="LOGIN" class="btn btn-success btn-block">Click <a href="facility.html"> HERE</a> for facility login</button>
</div>                       

</form>
<div>
    <h4 style="color: gray; text-align: center; font-weight: 200; padding-top: 30px;"> <strong style="color: gray; text-align: center; font-weight: 200;">© NASCOP</strong> - 1987 - 2023 | All Rights Reserved.</h4>
 </div>
                     
                        
                   

            </div>
    
    
</body>
</html>

survey/templates/survey/submit_success.html
{% load static %}
<link rel="stylesheet" href="{% static 'thanks.css' %}">
<div class="page-background">
  <div class="thanks">Thank</br> you!</div>
  <div class="thanks-text">
    <p class="page-text">Thank you for taking part in the survey. We whole heartedly appreciate it.</p>
    <a href="/survey/all_surveys" class="btn">Take Another Survey</a>
  </div>
</div>

survey/templates/survey/survey_details.html
{% load static %}
<link rel="stylesheet" href="{% static 'design.css'%}">
      <div class="card survey-form-card">
        <h5 class="card-header">{{survey.name}}</h5></br>
        <div class="images">
          <image src = "{% static 'kemri_logo.jpg'%}"></image>
        </div>
        <div class="card-body">
            <p class="card-text">Kindly fill in the survey and submit to participate</p>
            <form action="/survey/submit_survey/" method="post">
            {% csrf_token %}
            {% for question in survey.question_set.all %}
                <fieldset class="form-group">
                  <div class="row">
                    <legend class="col-form-label col-md-6 pt-0">{{question.question_text}}</legend>
                    <div class="col-md-6">
                      {% for choice in question.choice_set.all %}
                          <div class="form-check">
                            <input class="form-check-input" type="radio" name="{{question.id}}"
                                   id="{{question.id}}{{choice.id}}" value="choice/{{choice.id}}" aria-describedby="radioHelp" required>
                            <label class="form-check-label" for="{{question.id}}{{choice.id}}">
                              {{choice.choice_text}}
                            </label>
                          </div>
                      {% endfor %}
                      <small id="radioHelp" class="form-text text-muted">Please select one of the available choices.</small>
                    </div>
                  </div>
                </fieldset>
                <hr/>
            {% endfor %}
            <div class="form-group">
              <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </div>
          </form>
        </div>
      </div>

survey/templates/survey/surveys.html
{% load static %}
<link rel="stylesheet" href="{% static 'design.css'%}">

<div class="card">
  <h5 class="card-header">Available Surveys</h5>
  <div class="card-body">
      <p class="card-text">Participate in any survey to  help us understand you better!</p>
      <ul>
        {% for survey in surveys %}
            <li>
                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title"><a href="/survey/survey_details/{{survey.id}}">{{survey.name}}</a></h5>
                  </div>
                </div></br>
            </li>
        {% endfor %}
      </ul>
  </div>
</div>